/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package medical.solucoes.view;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import medical.solucoes.dao.DoctorDao;
import medical.solucoes.dao.EspecialidadeDao;
import medical.solucoes.dao.UsuarioDao;
import medical.solucoes.model.Doctor;
import medical.solucoes.model.Especialidade;
import medical.solucoes.model.Usuario;
import medical.tabelas.TableModelDoctors;

/**
 *
 * 
 */
public class IfrCadastroDoctors extends javax.swing.JInternalFrame {

    Doctor doctor = null;
    DoctorDao doctorDao = new DoctorDao();
    TableModelDoctors tableModel = null;
    int id=0;
    Boolean isEditing = false;
    public IfrCadastroDoctors() {
        initComponents(); 
        
        rbtnActive.setSelected(true);
        comboBoxEspecializacao.removeAllItems();
        ArrayList<Especialidade> especialidades = new EspecialidadeDao().listar();
         int i =0; 
         while (i<especialidades.size()){
              
             comboBoxEspecializacao.addItem(especialidades.get(i).getDescricao()); 
         i++;
         }
         new DoctorDao().popularTabela(tblDoc,"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        tbdCadastro = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfdCrm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfdNomeDoc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboBoxEspecializacao = new javax.swing.JComboBox<>();
        btnSalvarUsuario = new javax.swing.JButton();
        btnSalvarUsuario1 = new javax.swing.JButton();
        rbtnActive = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoc = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Médicos");

        tbdCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdCadastroMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("CRM");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("NOME");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("ESPECIALIZAÇÃO");

        comboBoxEspecializacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        comboBoxEspecializacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboBoxEspecializacaoMouseClicked(evt);
            }
        });
        comboBoxEspecializacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEspecializacaoActionPerformed(evt);
            }
        });

        btnSalvarUsuario.setText("NOVO");
        btnSalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarUsuarioActionPerformed(evt);
            }
        });

        btnSalvarUsuario1.setText("SALVAR");
        btnSalvarUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarUsuario1ActionPerformed(evt);
            }
        });

        rbtnActive.setText("Ativo");
        rbtnActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnActiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvarUsuario1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfdNomeDoc))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfdCrm))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxEspecializacao, 0, 521, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtnActive)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfdNomeDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdCrm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnActive)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        tbdCadastro.addTab("Cadastro", jPanel2);

        tblDoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDoc);

        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEdit)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEdit)
                .addGap(6, 6, 6))
        );

        tbdCadastro.addTab("Listagem", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tbdCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tbdCadastro)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarUsuarioActionPerformed
        limparFormulario(); 
    }//GEN-LAST:event_btnSalvarUsuarioActionPerformed

    private void tbdCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdCadastroMouseClicked
       
    }//GEN-LAST:event_tbdCadastroMouseClicked

    private void btnSalvarUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarUsuario1ActionPerformed
            
        if (this.doctor == null) {
            this.doctor = new Doctor(id,tfdNomeDoc.getText(),tfdCrm.getText(),new Especialidade()); 
        }

        this.doctor.setNome(tfdNomeDoc.getText());
        this.doctor.setCrm(tfdCrm.getText()); 
        this.doctor.setEspecializacao(new EspecialidadeDao().buscarDescricao(comboBoxEspecializacao.getItemAt(comboBoxEspecializacao.getSelectedIndex())));
        this.doctor.setAtivo(rbtnActive.isSelected());
        if (!isEditing) {
            if (this.doctorDao.salvar(this.doctor)) {
                JOptionPane.showMessageDialog(null,
                        "Registro inserido com sucesso", "Sucesso",
                        JOptionPane.INFORMATION_MESSAGE);  
                limparFormulario();
                isEditing=false;
                new DoctorDao().popularTabela(tblDoc,"");
            } else {
                JOptionPane.showMessageDialog(null,
                        "Erro ao salvar médico", "Erro de Validação",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (this.doctorDao.atualizar(this.doctor)) {
                JOptionPane.showMessageDialog(null,
                        "Registro atualizado com sucesso", "Sucesso",
                        JOptionPane.INFORMATION_MESSAGE); 
                limparFormulario();
                isEditing=false;
                new DoctorDao().popularTabela(tblDoc,"");
            } else {
                JOptionPane.showMessageDialog(null,
                        "Erro ao atualizar médico", "Erro de Validação",
                        JOptionPane.ERROR_MESSAGE);
            }
        } 
    }//GEN-LAST:event_btnSalvarUsuario1ActionPerformed

    private void comboBoxEspecializacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEspecializacaoActionPerformed
      
    }//GEN-LAST:event_comboBoxEspecializacaoActionPerformed

    private void comboBoxEspecializacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboBoxEspecializacaoMouseClicked
        String autocomplete = "";
        comboBoxEspecializacao.removeAllItems();
        Especialidade especialidade = new Especialidade();
         ArrayList<Especialidade> especialidades = new EspecialidadeDao().listar();
         int i =0;
         while (i<especialidades.size()){ 
             comboBoxEspecializacao.addItem(especialidades.get(i).getDescricao()); 
         i++;
         }
        comboBoxEspecializacao.showPopup();
    }//GEN-LAST:event_comboBoxEspecializacaoMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String idString = String.valueOf(tblDoc.getValueAt(tblDoc.getSelectedRow(), 0));

        id = Integer.parseInt(idString);

        Doctor  doctor = new DoctorDao().buscar(id);

        tbdCadastro.setSelectedIndex(0);

        tfdNomeDoc.setText(doctor.getNome());
        
        tfdCrm.setText(doctor.getCrm()); 
 
        if (doctor.isAtivo()==true){
        rbtnActive.setSelected(true);
        }
        else{
        rbtnActive.setSelected(false);
        }
        
        isEditing = true;
        comboBoxEspecializacao.setSelectedItem(doctor.getEspecializacao().getDescricao());  
    }//GEN-LAST:event_btnEditActionPerformed

    private void rbtnActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnActiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnActiveActionPerformed
 
    public void limparFormulario(){
        tfdNomeDoc.setText("");
        tfdCrm.setText("");
        rbtnActive.setSelected(true);
        isEditing=false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSalvarUsuario;
    private javax.swing.JButton btnSalvarUsuario1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> comboBoxEspecializacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox rbtnActive;
    private javax.swing.JTabbedPane tbdCadastro;
    private javax.swing.JTable tblDoc;
    private javax.swing.JTextField tfdCrm;
    private javax.swing.JTextField tfdNomeDoc;
    // End of variables declaration//GEN-END:variables
}
